### PR TITLE
Add email interaction tracking

### PR DESCRIPTION
**Pull request by snaily**
Start tracking the funnel through Google Analytics.

Please check that the naming and event trigger points are acceptable to you.

### CODE REVIEW

**Comment by subho007** [comment]
@snaily this looks good, deploying it in upstream

**Comment by snaily** [comment]
:+1: When can I expect it to be live?

**Comment by subho007** [comment]
@snaily it is live. Upstream branch goes live whenever the code is merged :+1:

**Comment by snaily** [comment]
Continuous integration :heart:

**Pull request merged**
